apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-image-compare #{{ include "container-image-compare.fullname" . }}
  labels:
    {{- include "container-image-compare.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "container-image-compare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "container-image-compare.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "container-image-compare.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "{{ .Values.config.port }}"
            - name: APP_DATA_DIR
              value: "/app/appdata"
            - name: MAX_CACHE_SIZE_GB
              value: "{{ .Values.config.maxCacheSizeGB }}"
            - name: MAX_HISTORY_ITEMS
              value: "{{ .Values.config.maxHistoryItems }}"
            {{- if .Values.proxy.httpProxy }}
            - name: HTTP_PROXY
              value: "{{ .Values.proxy.httpProxy }}"
            {{- end }}
            {{- if .Values.proxy.httpsProxy }}
            - name: HTTPS_PROXY
              value: "{{ .Values.proxy.httpsProxy }}"
            {{- end }}
            {{- if .Values.proxy.noProxy }}
            - name: NO_PROXY
              value: "{{ .Values.proxy.noProxy }}"
            {{- end }}
            {{- if .Values.config.insecureRegistries }}
            - name: INSECURE_REGISTRIES
              value: "{{ .Values.config.insecureRegistries }}"
            {{- end }}
            {{- if .Values.config.debugLogging }}
            - name: DEBUG_LOGGING
              value: "true"
            {{- end }}
            {{- if .Values.credentialKey }}
            - name: CIC_CRED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "container-image-compare.fullname" . }}-secret
                  key: credential-key
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /app/appdata
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: container-image-compare #{{ .Values.persistence.existingClaim | default (include "container-image-compare.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
