{{- if .Values.credentialKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "container-image-compare.fullname" . }}-secret
  labels:
    {{- include "container-image-compare.labels" . | nindent 4 }}
type: Opaque
data:
  credential-key: {{ .Values.credentialKey | b64enc | quote }}
{{- end }}
